steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg=GO_VERSION=$_GO_VERSION
      - --build-arg=TERRAFORM_VERSION=$_TERRAFORM_VERSION
      - --tag=gcr.io/$PROJECT_ID/e2e-runner:$_GO_VERSION-tf$_TERRAFORM_VERSION
      - .
images:
  - gcr.io/$PROJECT_ID/e2e-runner:$_GO_VERSION-tf$_TERRAFORM_VERSION
